// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_Uk2N7zaO6la1-n3OE4_1rwNJNGxMCBg',
    appId: '1:396744896249:web:c21a5370648b810e683c28',
    messagingSenderId: '396744896249',
    projectId: 'mano-54cf7',
    authDomain: 'mano-54cf7.firebaseapp.com',
    databaseURL: 'https://mano-54cf7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mano-54cf7.firebasestorage.app',
    measurementId: 'G-2DL630Z969',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhv_JNbDII5PZYrqLGEM_AH1EbNHwgwSU',
    appId: '1:396744896249:android:1c8567f9761befa6683c28',
    messagingSenderId: '396744896249',
    projectId: 'mano-54cf7',
    databaseURL: 'https://mano-54cf7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mano-54cf7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRrkDa634sZrWvLkyMMLi12yi657BXGKo',
    appId: '1:396744896249:ios:609a6870cbf838dc683c28',
    messagingSenderId: '396744896249',
    projectId: 'mano-54cf7',
    databaseURL: 'https://mano-54cf7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mano-54cf7.firebasestorage.app',
    iosBundleId: 'com.example.ninexmanoMatrix',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRrkDa634sZrWvLkyMMLi12yi657BXGKo',
    appId: '1:396744896249:ios:609a6870cbf838dc683c28',
    messagingSenderId: '396744896249',
    projectId: 'mano-54cf7',
    databaseURL: 'https://mano-54cf7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mano-54cf7.firebasestorage.app',
    iosBundleId: 'com.example.ninexmanoMatrix',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_Uk2N7zaO6la1-n3OE4_1rwNJNGxMCBg',
    appId: '1:396744896249:web:99de79c860ba2ec1683c28',
    messagingSenderId: '396744896249',
    projectId: 'mano-54cf7',
    authDomain: 'mano-54cf7.firebaseapp.com',
    databaseURL: 'https://mano-54cf7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mano-54cf7.firebasestorage.app',
    measurementId: 'G-5NNQ506XST',
  );
}
